theme: jekyll-theme-cayman
title: Urbit on ARM
description: Guide to running Urbit on (non-Apple) ARM powered devices
show_buttons: "true"
twitter:
  username: botter_nidnul
  card: summary
defaults:
  - scope:
      path: ""
    values:
      image: /assets/logo.jpg
gems:
  - jekyll-redirect-from
